[profile.default]
src = 'contracts'
test = 'test/foundry'
libs = ['lib']
solc_version = '0.8.28'
optimizer = true
optimizer_runs = 200
via_ir = true

gas_reports = ['*']
no_match_coverage = '.*/mocks/.*|contracts/modules/contests/ContestFactory.sol|contracts/modules/contests/ContestValidator.sol|contracts/modules/marketplace/MarketplaceFactory.sol'
