name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - uses: actions/checkout@v3

      # 2) Set up Node.js (for Hardhat / front-end)
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3) Install Foundry toolchain
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # 4) Install Solidity library dependencies
      - name: Forge install libraries
        run: |
          forge install foundry-rs/forge-std
          forge install OpenZeppelin/openzeppelin-contracts@v5.3.0
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.3.0

      # 5) Install JS dependencies
      - name: Install NPM dependencies
        run: npm install

      # 6) Install Slither for static analysis
      - name: Install Slither
        run: |
          python3 -m pip install --user slither-analyzer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # 7) Run Foundry tests with coverage enforcement
      - name: Forge coverage
        run: |
          forge coverage --report lcov --ir-minimum
          bash scripts/check-coverage.sh 70

      # 8) Compile contracts with Hardhat
      - name: Hardhat compile
        run: npx hardhat compile

      # 9) Run demo scripts
      - name: Run demo scripts
        run: |
          for f in scripts/demo/*.ts; do
            npx hardhat run "$f" || exit 1
          done

      # 10) Hardhat coverage (using solidity-coverage)
      - name: Hardhat coverage
        run: npm run coverage

      # 11) Static analysis with Slither
      - name: Slither static
        run: bash scripts/security/run-slither.sh --critical-only
