name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - uses: actions/checkout@v3

      # 2) Set up Node.js (for Hardhat / front-end)
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3) Install Foundry toolchain
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      # 4) Install Solidity library dependencies
      - name: Forge install libraries
        run: |
          forge install foundry-rs/forge-std
          forge install OpenZeppelin/openzeppelin-contracts@v5.3.0
          forge install OpenZeppelin/openzeppelin-contracts-upgradeable@v5.3.0

      # 5) Install JS dependencies
      - name: Install NPM dependencies
        run: npm install

      # 6) Run Foundry unit and fuzz tests
      - name: Run Foundry tests
        run: forge test -vv

      # 7) Compile contracts with Hardhat
      - name: Hardhat compile
        run: npx hardhat compile

      # 8) Run Hardhat JS tests (e2e/integration)
      - name: Run Hardhat tests
        run: npx hardhat test

      # 9) Run showcase scripts
      - name: Run showcase scripts
        run: |
          for f in scripts/showcase*.ts; do
            npx hardhat run "$f" || exit 1
          done

      # 10) Forge coverage report + coverage gate (≥90%)
      - name: Forge coverage
        run: |
          forge coverage --report lcov
          bash scripts/check-coverage.sh 90

      # 11) Hardhat coverage (using solidity-coverage)
      - name: Hardhat coverage
        run: npm run coverage

      # 12) Static analysis with Slither
      - name: Slither static
        run: slither . --fail-on-issue High
