name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup
      - run: forge install foundry-rs/forge-std OpenZeppelin/openzeppelin-contracts@v5.3.0 OpenZeppelin/openzeppelin-contracts-upgradeable@v5.3.0
      - run: forge test -vv
      - run: npx hardhat test
      - name: Forge Coverage
        run: |
          forge coverage --report lcov
          bash .github/check-coverage.sh 90
      - name: Hardhat Coverage
        run: npm run coverage:hardhat
      - name: Slither Static Analysis
        run: slither . --fail-on-issue High

